---
title: "Using the Package"
output: 
    github_document:
        toc: true
        toc_depth: 1
        html_preview: true
    html_document:
        toc: true
        toc_depth: 1
        number_sections: true
---

## Running the Rasch Model

```{r output = FALSE}
library(rebl)

# Example data frame
str(raw_example)

# Identify REBL items with regex. 
# Here we take everything that does not start with 'res'
(rebl_items <- id_rebl_items(raw_example, '^(?!res).*', perl = TRUE))

# Recode REBL items from Yes/No to 1/0
df <- recode_rebl(raw_example, rebl_items)

# To reverse code reversed REBL items (where 0 is the PEB), first identify them.
# Just using all food items as an example
(reversed_items <- id_reversed_rebl_items(rebl_items, '^food'))

# Now recode the reversed items in the df
df <- reverse_code_rebl_items(df, reversed_items)
```

## Getting REBL Scores

```{r output = FALSE}
# Run Rasch Model
model <- get_rasch_model(df, 'respondent_id', rebl_items)

# Throws warning if some items are not found in df
model <- get_rasch_model(df, 'respondent_id', c(rebl_items, 'ffff', 'zzzz'))

# Get a df of REBL scores and person fit statistics
rebl_scores <- get_rebl_scores(model)

# Only REBL scores, no fits
rebl_only <- get_rebl_scores(model, include_fits = FALSE)
```
